
services:
  backend:
    build:
      context: ./kombo-connect-bff
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./kombo-connect-bff/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./kombo-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    env_file:
      - ./kombo-frontend/.env
    depends_on:
      - backend


  db:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
